.include "macro.inc"

.section .bss

/* Generated by spimdisasm 1.26.0 */

dlabel D_8003BAD0
/* 3C6D0 8003BAD0 */ .space 0x21B0

dlabel D_8003DC80
/* 3E880 8003DC80 */ .space 0x100

dlabel D_8003DD80
/* 3E980 8003DD80 */ .space 0x18

dlabel D_8003DD98
/* 3E998 8003DD98 */ .space 0x08

dlabel D_8003DDA0
/* 3E9A0 8003DDA0 */ .space 0x02

dlabel D_8003DDA2
/* 3E9A2 8003DDA2 */ .space 0x02

dlabel D_8003DDA4
/* 3E9A4 8003DDA4 */ .space 0x04

dlabel D_8003DDA8
/* 3E9A8 8003DDA8 */ .space 0x04

dlabel D_8003DDAC
/* 3E9AC 8003DDAC */ .space 0x04

dlabel D_8003DDB0
/* 3E9B0 8003DDB0 */ .space 0x08

dlabel D_8003DDB8
/* 3E9B8 8003DDB8 */ .space 0x04

dlabel D_8003DDBC
/* 3E9BC 8003DDBC */ .space 0x01

dlabel D_8003DDBD
/* 3E9BD 8003DDBD */ .space 0x01

dlabel D_8003DDBE
/* 3E9BE 8003DDBE */ .space 0x01

dlabel D_8003DDBF
/* 3E9BF 8003DDBF */ .space 0x01

dlabel D_8003DDC0
/* 3E9C0 8003DDC0 */ .space 0x01

dlabel D_8003DDC1
/* 3E9C1 8003DDC1 */ .space 0x03

dlabel D_8003DDC4
/* 3E9C4 8003DDC4 */ .space 0x04

dlabel D_8003DDC8
/* 3E9C8 8003DDC8 */ .space 0x68

dlabel D_8003DE30
/* 3EA30 8003DE30 */ .space 0x27C

dlabel D_8003E0AC
/* 3ECAC 8003E0AC */ .space 0x2014

dlabel D_800400C0
/* 40CC0 800400C0 */ .space 0x2000

dlabel D_800420C0
/* 42CC0 800420C0 */ .space 0x2000

dlabel D_800440C0
/* 44CC0 800440C0 */ .space 0x38

dlabel D_800440F8
/* 44CF8 800440F8 */ .space 0xE0

dlabel D_800441D8
/* 44DD8 800441D8 */ .space 0x398

dlabel D_80044570
/* 45170 80044570 */ .space 0x04

dlabel D_80044574
/* 45174 80044574 */ .space 0x04

dlabel D_80044578
/* 45178 80044578 */ .space 0x08

dlabel D_80044580
/* 45180 80044580 */ .space 0x10

dlabel D_80044590
/* 45190 80044590 */ .space 0x10

dlabel D_800445A0
/* 451A0 800445A0 */ .space 0x04

dlabel D_800445A4
/* 451A4 800445A4 */ .space 0x04

dlabel D_800445A8
/* 451A8 800445A8 */ .space 0x08

dlabel D_800445B0
/* 451B0 800445B0 */ .space 0x21B0

dlabel D_80046760
/* 47360 80046760 */ .space 0x08

dlabel D_80046768
/* 47368 80046768 */ .space 0x18

dlabel D_80046780
/* 47380 80046780 */ .space 0x40

dlabel D_800467C0
/* 473C0 800467C0 */ .space 0x18

dlabel D_800467D8
/* 473D8 800467D8 */ .space 0x08

dlabel D_800467E0
/* 473E0 800467E0 */ .space 0x18

dlabel D_800467F8
/* 473F8 800467F8 */ .space 0x04

dlabel D_800467FC
/* 473FC 800467FC */ .space 0x04

dlabel D_80046800
/* 47400 80046800 */ .space 0x08

dlabel D_80046808
/* 47408 80046808 */ .space 0x08

dlabel D_80046810
/* 47410 80046810 */ .space 0x18

dlabel D_80046828
/* 47428 80046828 */ .space 0x08

dlabel D_80046830
/* 47430 80046830 */ .space 0x14

dlabel D_80046844
/* 47444 80046844 */ .space 0x14

dlabel D_80046858
/* 47458 80046858 */ .space 0x08

dlabel D_80046860
/* 47460 80046860 */ .space 0x800

dlabel D_80047060
/* 47C60 80047060 */ .space 0x02

dlabel D_80047062
/* 47C62 80047062 */ .space 0x02

dlabel D_80047064
/* 47C64 80047064 */ .space 0x02

dlabel D_80047066
/* 47C66 80047066 */ .space 0x0A

dlabel D_80047070
/* 47C70 80047070 */ .space 0x1000

dlabel D_80048070
/* 48C70 80048070 */ .space 0x200

dlabel D_80048270
/* 48E70 80048270 */ .space 0x04

dlabel D_80048274
/* 48E74 80048274 */ .space 0x04

dlabel D_80048278
/* 48E78 80048278 */ .space 0x04

dlabel D_8004827C
/* 48E7C 8004827C */ .space 0x04

dlabel D_80048280
/* 48E80 80048280 */ .space 0x08

dlabel D_80048288
/* 48E88 80048288 */ .space 0x08

dlabel D_80048290
/* 48E90 80048290 */ .space 0x08

dlabel D_80048298
/* 48E98 80048298 */ .space 0x08

dlabel D_800482A0
/* 48EA0 800482A0 */ .space 0x08

dlabel D_800482A8
/* 48EA8 800482A8 */ .space 0x08

dlabel D_800482B0
/* 48EB0 800482B0 */ .space 0x08

dlabel D_800482B8
/* 48EB8 800482B8 */ .space 0x08

dlabel D_800482C0
/* 48EC0 800482C0 */ .space 0x10

dlabel D_800482D0
/* 48ED0 800482D0 */ .space 0x04

dlabel D_800482D4
/* 48ED4 800482D4 */ .space 0x04

dlabel D_800482D8
/* 48ED8 800482D8 */ .space 0x02

dlabel D_800482DA
/* 48EDA 800482DA */ .space 0x06

dlabel D_800482E0
/* 48EE0 800482E0 */ .space 0x04

dlabel D_800482E4
/* 48EE4 800482E4 */ .space 0x0C

dlabel D_800482F0
/* 48EF0 800482F0 */ .space 0x18

dlabel D_80048308
/* 48F08 80048308 */ .space 0x08

dlabel D_80048310
/* 48F10 80048310 */ .space 0x10

dlabel D_80048320
/* 48F20 80048320 */ .space 0x02

dlabel D_80048322
/* 48F22 80048322 */ .space 0x01

dlabel D_80048323
/* 48F23 80048323 */ .space 0x01

dlabel D_80048324
/* 48F24 80048324 */ .space 0x14

dlabel D_80048338
/* 48F38 80048338 */ .space 0x18

dlabel D_80048350
/* 48F50 80048350 */ .space 0x1A0

dlabel D_800484F0
/* 490F0 800484F0 */ .space 0x01

dlabel D_800484F1
/* 490F1 800484F1 */ .space 0x01

dlabel D_800484F2
/* 490F2 800484F2 */ .space 0x01

dlabel D_800484F3
/* 490F3 800484F3 */ .space 0x01

dlabel D_800484F4
/* 490F4 800484F4 */ .space 0x04

dlabel D_800484F8
/* 490F8 800484F8 */ .space 0x04

dlabel D_800484FC
/* 490FC 800484FC */ .space 0x04

dlabel D_80048500
/* 49100 80048500 */ .space 0x40

dlabel D_80048540
/* 49140 80048540 */ .space 0x40

dlabel D_80048580
/* 49180 80048580 */ .space 0x04

dlabel D_80048584
/* 49184 80048584 */ .space 0x04

dlabel D_80048588
/* 49188 80048588 */ .space 0x08

dlabel D_80048590
/* 49190 80048590 */ .space 0x04

dlabel D_80048594
/* 49194 80048594 */ .space 0x04

dlabel D_80048598
/* 49198 80048598 */ .space 0x04

dlabel D_8004859C
/* 4919C 8004859C */ .space 0x04

dlabel D_800485A0
/* 491A0 800485A0 */ .space 0x10

dlabel D_800485B0
/* 491B0 800485B0 */ .space 0x20

dlabel D_800485D0
/* 491D0 800485D0 */ .space 0x20

dlabel D_800485F0
/* 491F0 800485F0 */ .space 0x200

dlabel D_800487F0
/* 493F0 800487F0 */ .space 0x8000

dlabel D_800507F0
/* 513F0 800507F0 */ .space 0x10

dlabel D_80050800
/* 51400 80050800 */ .space 0xFD0

dlabel D_800517D0
/* 523D0 800517D0 */ .space 0x18

dlabel D_800517E8
/* 523E8 800517E8 */ .space 0x4EF8

dlabel D_800566E0
/* 572E0 800566E0 */ .space 0x08

dlabel D_800566E8
/* 572E8 800566E8 */ .space 0x08

dlabel D_800566F0
/* 572F0 800566F0 */ .space 0x250

dlabel D_80056940
/* 57540 80056940 */ .space 0x08

dlabel D_80056948
/* 57548 80056948 */ .space 0x08

dlabel D_80056950
/* 57550 80056950 */ .space 0x04

dlabel D_80056954
/* 57554 80056954 */ .space 0x14

dlabel D_80056968
/* 57568 80056968 */ .space 0x358

dlabel D_80056CC0
/* 578C0 80056CC0 */ .space 0x370

dlabel D_80057030
/* 57C30 80057030 */ .space 0x08

dlabel D_80057038
/* 57C38 80057038 */ .space 0x10

dlabel D_80057048
/* 57C48 80057048 */ .space 0x13B0

dlabel D_800583F8
/* 58FF8 800583F8 */ .space 0x3F4

dlabel D_800587EC
/* 593EC 800587EC */ .space 0x04

dlabel D_800587F0
/* 593F0 800587F0 */ .space 0x108

dlabel D_800588F8
/* 594F8 800588F8 */ .space 0x08

dlabel D_80058900
/* 59500 80058900 */ .space 0x84

dlabel D_80058984
/* 59584 80058984 */ .space 0x04

dlabel D_80058988
/* 59588 80058988 */ .space 0x84

dlabel D_80058A0C
/* 5960C 80058A0C */ .space 0x04

dlabel D_80058A10
/* 59610 80058A10 */ .space 0x580

dlabel D_80058F90
/* 59B90 80058F90 */ .space 0x10

dlabel D_80058FA0
/* 59BA0 80058FA0 */ .space 0x580

dlabel D_80059520
/* 5A120 80059520 */ .space 0x08

dlabel D_80059528
/* 5A128 80059528 */ .space 0x370

dlabel D_80059898
/* 5A498 80059898 */ .space 0x08

dlabel D_800598A0
/* 5A4A0 800598A0 */ .space 0x370

dlabel D_80059C10
/* 5A810 80059C10 */ .space 0x08

dlabel D_80059C18
/* 5A818 80059C18 */ .space 0xB0

dlabel D_80059CC8
/* 5A8C8 80059CC8 */ .space 0x08

dlabel D_80059CD0
/* 5A8D0 80059CD0 */ .space 0xB0

dlabel D_80059D80
/* 5A980 80059D80 */ .space 0x02

dlabel D_80059D82
/* 5A982 80059D82 */ .space 0x0E

dlabel D_80059D90
/* 5A990 80059D90 */ .space 0x0C

dlabel D_80059D9C
/* 5A99C 80059D9C */ .space 0x0C

dlabel D_80059DA8
/* 5A9A8 80059DA8 */ .space 0x358

dlabel D_8005A100
/* 5AD00 8005A100 */ .space 0x18

dlabel D_8005A118
/* 5AD18 8005A118 */ .space 0x88

dlabel D_8005A1A0
/* 5ADA0 8005A1A0 */ .space 0x02

dlabel D_8005A1A2
/* 5ADA2 8005A1A2 */ .space 0x02

dlabel D_8005A1A4
/* 5ADA4 8005A1A4 */ .space 0x04

dlabel D_8005A1A8
/* 5ADA8 8005A1A8 */ .space 0x04

dlabel D_8005A1AC
/* 5ADAC 8005A1AC */ .space 0x08

dlabel D_8005A1B4
/* 5ADB4 8005A1B4 */ .space 0x04

dlabel D_8005A1B8
/* 5ADB8 8005A1B8 */ .space 0x08

dlabel D_8005A1C0
/* 5ADC0 8005A1C0 */ .space 0x04

dlabel D_8005A1C4
/* 5ADC4 8005A1C4 */ .space 0x04

dlabel D_8005A1C8
/* 5ADC8 8005A1C8 */ .space 0x28

dlabel D_8005A1F0
/* 5ADF0 8005A1F0 */ .space 0x190

dlabel D_8005A380
/* 5AF80 8005A380 */ .space 0x02

dlabel D_8005A382
/* 5AF82 8005A382 */ .space 0x2E

dlabel D_8005A3B0
/* 5AFB0 8005A3B0 */ .space 0x10

dlabel D_8005A3C0
/* 5AFC0 8005A3C0 */ .space 0x370

dlabel D_8005A730
/* 5B330 8005A730 */ .space 0x370

dlabel D_8005AAA0
/* 5B6A0 8005AAA0 */ .space 0x0C

dlabel D_8005AAAC
/* 5B6AC 8005AAAC */ .space 0x01

dlabel D_8005AAAD
/* 5B6AD 8005AAAD */ .space 0x01

dlabel D_8005AAAE
/* 5B6AE 8005AAAE */ .space 0x01

dlabel D_8005AAAF
/* 5B6AF 8005AAAF */ .space 0x31

dlabel D_8005AAE0
/* 5B6E0 8005AAE0 */ .space 0x08

dlabel D_8005AAE8
/* 5B6E8 8005AAE8 */ .space 0x58

dlabel D_8005AB40
/* 5B740 8005AB40 */ .space 0x08

dlabel D_8005AB48
/* 5B748 8005AB48 */ .space 0x58

dlabel D_8005ABA0
/* 5B7A0 8005ABA0 */ .space 0x08

dlabel D_8005ABA8
/* 5B7A8 8005ABA8 */ .space 0x84

dlabel D_8005AC2C
/* 5B82C 8005AC2C */ .space 0x04

dlabel D_8005AC30
/* 5B830 8005AC30 */ .space 0x84

dlabel D_8005ACB4
/* 5B8B4 8005ACB4 */ .space 0x04

dlabel D_8005ACB8
/* 5B8B8 8005ACB8 */ .space 0x84

dlabel D_8005AD3C
/* 5B93C 8005AD3C */ .space 0x04

dlabel D_8005AD40
/* 5B940 8005AD40 */ .space 0x84

dlabel D_8005ADC4
/* 5B9C4 8005ADC4 */ .space 0x04

dlabel D_8005ADC8
/* 5B9C8 8005ADC8 */ .space 0x84

dlabel D_8005AE4C
/* 5BA4C 8005AE4C */ .space 0x04

dlabel D_8005AE50
/* 5BA50 8005AE50 */ .space 0x58

dlabel D_8005AEA8
/* 5BAA8 8005AEA8 */ .space 0x08

dlabel D_8005AEB0
/* 5BAB0 8005AEB0 */ .space 0x134

dlabel D_8005AFE4
/* 5BBE4 8005AFE4 */ .space 0x04

dlabel D_8005AFE8
/* 5BBE8 8005AFE8 */ .space 0x84

dlabel D_8005B06C
/* 5BC6C 8005B06C */ .space 0x04

dlabel D_8005B070
/* 5BC70 8005B070 */ .space 0x88

dlabel D_8005B0F8
/* 5BCF8 8005B0F8 */ .space 0x18

dlabel D_8005B110
/* 5BD10 8005B110 */ .space 0x108

dlabel D_8005B218
/* 5BE18 8005B218 */ .space 0x08

dlabel D_8005B220
/* 5BE20 8005B220 */ .space 0x04

dlabel D_8005B224
/* 5BE24 8005B224 */ .space 0xCC

dlabel D_8005B2F0
/* 5BEF0 8005B2F0 */ .space 0x51B0

dlabel D_800604A0
/* 610A0 800604A0 */ .space 0x04

dlabel D_800604A4
/* 610A4 800604A4 */ .space 0x04

dlabel D_800604A8
/* 610A8 800604A8 */ .space 0x10

dlabel D_800604B8
/* 610B8 800604B8 */ .space 0x04

dlabel D_800604BC
/* 610BC 800604BC */ .space 0x0C

dlabel D_800604C8
/* 610C8 800604C8 */ .space 0x04

dlabel D_800604CC
/* 610CC 800604CC */ .space 0x04

dlabel D_800604D0
/* 610D0 800604D0 */ .space 0x04

dlabel D_800604D4
/* 610D4 800604D4 */ .space 0x04

dlabel D_800604D8
/* 610D8 800604D8 */ .space 0x04

dlabel D_800604DC
/* 610DC 800604DC */ .space 0x04

dlabel D_800604E0
/* 610E0 800604E0 */ .space 0x04

dlabel D_800604E4
/* 610E4 800604E4 */ .space 0x02

dlabel D_800604E6
/* 610E6 800604E6 */ .space 0x02

dlabel D_800604E8
/* 610E8 800604E8 */ .space 0x04

dlabel D_800604EC
/* 610EC 800604EC */ .space 0x04

dlabel D_800604F0
/* 610F0 800604F0 */ .space 0x04

dlabel D_800604F4
/* 610F4 800604F4 */ .space 0x04

dlabel D_800604F8
/* 610F8 800604F8 */ .space 0x04

dlabel D_800604FC
/* 610FC 800604FC */ .space 0x04

dlabel D_80060500
/* 61100 80060500 */ .space 0x04

dlabel D_80060504
/* 61104 80060504 */ .space 0x04

dlabel D_80060508
/* 61108 80060508 */ .space 0x04

dlabel D_8006050C
/* 6110C 8006050C */ .space 0x04

dlabel D_80060510
/* 61110 80060510 */ .space 0x2010

dlabel D_80062520
/* 63120 80062520 */ .space 0x04

dlabel D_80062524
/* 63124 80062524 */ .space 0x04

dlabel D_80062528
/* 63128 80062528 */ .space 0x04

dlabel D_8006252C
/* 6312C 8006252C */ .space 0x04

dlabel D_80062530
/* 63130 80062530 */ .space 0x04

dlabel D_80062534
/* 63134 80062534 */ .space 0x04

dlabel D_80062538
/* 63138 80062538 */ .space 0x08

dlabel D_80062540
/* 63140 80062540 */ .space 0x18

dlabel D_80062558
/* 63158 80062558 */ .space 0x04

dlabel D_8006255C
/* 6315C 8006255C */ .space 0x04

dlabel D_80062560
/* 63160 80062560 */ .space 0x04

dlabel D_80062564
/* 63164 80062564 */ .space 0x04

dlabel D_80062568
/* 63168 80062568 */ .space 0x04

dlabel D_8006256C
/* 6316C 8006256C */ .space 0x04

dlabel D_80062570
/* 63170 80062570 */ .space 0x04

dlabel D_80062574
/* 63174 80062574 */ .space 0x0C

dlabel D_80062580
/* 63180 80062580 */ .space 0x04

dlabel D_80062584
/* 63184 80062584 */ .space 0x0C

dlabel D_80062590
/* 63190 80062590 */ .space 0x08

dlabel D_80062598
/* 63198 80062598 */ .space 0x04

dlabel D_8006259C
/* 6319C 8006259C */ .space 0x04

dlabel D_800625A0
/* 631A0 800625A0 */ .space 0x08

dlabel D_800625A8
/* 631A8 800625A8 */ .space 0x04

dlabel D_800625AC
/* 631AC 800625AC */ .space 0x04

dlabel D_800625B0
/* 631B0 800625B0 */ .space 0x08

dlabel D_800625B8
/* 631B8 800625B8 */ .space 0x04

dlabel D_800625BC
/* 631BC 800625BC */ .space 0x04

dlabel D_800625C0
/* 631C0 800625C0 */ .space 0x3C

dlabel D_800625FC
/* 631FC 800625FC */ .space 0xC4

dlabel D_800626C0
/* 632C0 800626C0 */ .space 0x11B0

dlabel D_80063870
/* 64470 80063870 */ .space 0x18

dlabel D_80063888
/* 64488 80063888 */ .space 0x08

dlabel D_80063890
/* 64490 80063890 */ .space 0x08

dlabel D_80063898
/* 64498 80063898 */ .space 0x11B8

dlabel D_80064A50
/* 65650 80064A50 */ .space 0x18

dlabel D_80064A68
/* 65668 80064A68 */ .space 0x18

dlabel D_80064A80
/* 65680 80064A80 */ .space 0x02

dlabel D_80064A82
/* 65682 80064A82 */ .space 0x02

dlabel D_80064A84
/* 65684 80064A84 */ .space 0x14

dlabel D_80064A98
/* 65698 80064A98 */ .space 0x02

dlabel D_80064A9A
/* 6569A 80064A9A */ .space 0x02

dlabel D_80064A9C
/* 6569C 80064A9C */ .space 0x14

dlabel D_80064AB0
/* 656B0 80064AB0 */ .space 0x10

dlabel D_80064AC0
/* 656C0 80064AC0 */ .space 0x10

dlabel D_80064AD0
/* 656D0 80064AD0 */ .space 0x04

dlabel D_80064AD4
/* 656D4 80064AD4 */ .space 0x04

dlabel D_80064AD8
/* 656D8 80064AD8 */ .space 0x648

dlabel D_80065120
/* 65D20 80065120 */ .space 0x08

dlabel D_80065128
/* 65D28 80065128 */ .space 0x04

dlabel D_8006512C
/* 65D2C 8006512C */ .space 0x01

dlabel D_8006512D
/* 65D2D 8006512D */ .space 0x01

dlabel D_8006512E
/* 65D2E 8006512E */ .space 0x01

dlabel D_8006512F
/* 65D2F 8006512F */ .space 0x01

dlabel D_80065130
/* 65D30 80065130 */ .space 0x01

dlabel D_80065131
/* 65D31 80065131 */ .space 0x03

dlabel D_80065134
/* 65D34 80065134 */ .space 0x04

dlabel D_80065138
/* 65D38 80065138 */ .space 0x68

dlabel D_800651A0
/* 65DA0 800651A0 */ .space 0x18

dlabel D_800651B8
/* 65DB8 800651B8 */ .space 0x04

dlabel D_800651BC
/* 65DBC 800651BC */ .space 0xC0

dlabel D_8006527C
/* 65E7C 8006527C */ .space 0x18

dlabel D_80065294
/* 65E94 80065294 */ .space 0xDA8

dlabel D_8006603C
/* 66C3C 8006603C */ .space 0x18

dlabel D_80066054
/* 66C54 80066054 */ .space 0x27C

dlabel D_800662D0
/* 66ED0 800662D0 */ .space 0x18

dlabel D_800662E8
/* 66EE8 800662E8 */ .space 0x6E4

dlabel D_800669CC
/* 675CC 800669CC */ .space 0x02

dlabel D_800669CE
/* 675CE 800669CE */ .space 0x36E2

dlabel D_8006A0B0
/* 6ACB0 8006A0B0 */ .space 0x1B0

dlabel D_8006A260
/* 6AE60 8006A260 */ .space 0x38

dlabel D_8006A298
/* 6AE98 8006A298 */ .space 0x04

dlabel D_8006A29C
/* 6AE9C 8006A29C */ .space 0x04

dlabel D_8006A2A0
/* 6AEA0 8006A2A0 */ .space 0x04

dlabel D_8006A2A4
/* 6AEA4 8006A2A4 */ .space 0x0C

dlabel D_8006A2B0
/* 6AEB0 8006A2B0 */ .space 0x02

dlabel D_8006A2B2
/* 6AEB2 8006A2B2 */ .space 0x3EC6

dlabel D_8006E178
/* 6ED78 8006E178 */ .space 0x30

dlabel D_8006E1A8
/* 6EDA8 8006E1A8 */ .space 0x08

dlabel D_8006E1B0
/* 6EDB0 8006E1B0 */ .space 0x1C0

dlabel D_8006E370
/* 6EF70 8006E370 */ .space 0x38

dlabel D_8006E3A8
/* 6EFA8 8006E3A8 */ .space 0x38

dlabel D_8006E3E0
/* 6EFE0 8006E3E0 */ .space 0x60

dlabel D_8006E440
/* 6F040 8006E440 */ .space 0x2010

dlabel D_80070450
/* 71050 80070450 */ .space 0x08

dlabel D_80070458
/* 71058 80070458 */ .space 0x04

dlabel D_8007045C
/* 7105C 8007045C */ .space 0x1C

dlabel D_80070478
/* 71078 80070478 */ .space 0x01

dlabel D_80070479
/* 71079 80070479 */ .space 0x07

dlabel D_80070480
/* 71080 80070480 */ .space 0x08

dlabel D_80070488
/* 71088 80070488 */ .space 0x04

dlabel D_8007048C
/* 7108C 8007048C */ .space 0x04

dlabel D_80070490
/* 71090 80070490 */ .space 0x04

dlabel D_80070494
/* 71094 80070494 */ .space 0x20C

dlabel D_800706A0
/* 712A0 800706A0 */ .space 0x04

dlabel D_800706A4
/* 712A4 800706A4 */ .space 0x04

dlabel D_800706A8
/* 712A8 800706A8 */ .space 0x02

dlabel D_800706AA
/* 712AA 800706AA */ .space 0x02

dlabel D_800706AC
/* 712AC 800706AC */ .space 0x02

dlabel D_800706AE
/* 712AE 800706AE */ .space 0x02

dlabel D_800706B0
/* 712B0 800706B0 */ .space 0x04

dlabel D_800706B4
/* 712B4 800706B4 */ .space 0x04

dlabel D_800706B8
/* 712B8 800706B8 */ .space 0x04

dlabel D_800706BC
/* 712BC 800706BC */ .space 0x04

dlabel D_800706C0
/* 712C0 800706C0 */ .space 0x02

dlabel D_800706C2
/* 712C2 800706C2 */ .space 0x02

dlabel D_800706C4
/* 712C4 800706C4 */ .space 0x40

dlabel D_80070704
/* 71304 80070704 */ .space 0x1A

dlabel D_8007071E
/* 7131E 8007071E */ .space 0x02

dlabel D_80070720
/* 71320 80070720 */ .space 0x04

dlabel D_80070724
/* 71324 80070724 */ .space 0x04

dlabel D_80070728
/* 71328 80070728 */ .space 0x04

dlabel D_8007072C
/* 7132C 8007072C */ .space 0x0C

dlabel D_80070738
/* 71338 80070738 */ .space 0x32

dlabel D_8007076A
/* 7136A 8007076A */ .space 0x02

dlabel D_8007076C
/* 7136C 8007076C */ .space 0x04

dlabel D_80070770
/* 71370 80070770 */ .space 0x04

dlabel D_80070774
/* 71374 80070774 */ .space 0x04

dlabel D_80070778
/* 71378 80070778 */ .space 0x28

dlabel D_800707A0
/* 713A0 800707A0 */ .space 0x02

dlabel D_800707A2
/* 713A2 800707A2 */ .space 0x2F6

dlabel D_80070A98
/* 71698 80070A98 */ .space 0x08

dlabel D_80070AA0
/* 716A0 80070AA0 */ .space 0x05

dlabel D_80070AA5
/* 716A5 80070AA5 */ .space 0x01

dlabel D_80070AA6
/* 716A6 80070AA6 */ .space 0x01

dlabel D_80070AA7
/* 716A7 80070AA7 */ .space 0x01

dlabel D_80070AA8
/* 716A8 80070AA8 */ .space 0x01

dlabel D_80070AA9
/* 716A9 80070AA9 */ .space 0x6B

dlabel D_80070B14
/* 71714 80070B14 */ .space 0x0C

dlabel D_80070B20
/* 71720 80070B20 */ .space 0x04

dlabel D_80070B24
/* 71724 80070B24 */ .space 0x04

dlabel D_80070B28
/* 71728 80070B28 */ .space 0x04

dlabel D_80070B2C
/* 7172C 80070B2C */ .space 0x04

dlabel D_80070B30
/* 71730 80070B30 */ .space 0x04

dlabel D_80070B34
/* 71734 80070B34 */ .space 0x10C

dlabel D_80070C40
/* 71840 80070C40 */ .space 0x04

dlabel D_80070C44
/* 71844 80070C44 */ .space 0x08

dlabel D_80070C4C
/* 7184C 80070C4C */ .space 0x04

dlabel D_80070C50
/* 71850 80070C50 */ .space 0x04

dlabel D_80070C54
/* 71854 80070C54 */ .space 0x1C

dlabel D_80070C70
/* 71870 80070C70 */ .space 0x04

dlabel D_80070C74
/* 71874 80070C74 */ .space 0x04

dlabel D_80070C78
/* 71878 80070C78 */ .space 0x10

dlabel D_80070C88
/* 71888 80070C88 */ .space 0x04

dlabel D_80070C8C
/* 7188C 80070C8C */ .space 0x04

dlabel D_80070C90
/* 71890 80070C90 */ .space 0x04

dlabel D_80070C94
/* 71894 80070C94 */ .space 0x04

dlabel D_80070C98
/* 71898 80070C98 */ .space 0x04

dlabel D_80070C9C
/* 7189C 80070C9C */ .space 0x04

dlabel D_80070CA0
/* 718A0 80070CA0 */ .space 0x04

dlabel D_80070CA4
/* 718A4 80070CA4 */ .space 0x04

dlabel D_80070CA8
/* 718A8 80070CA8 */ .space 0x04

dlabel D_80070CAC
/* 718AC 80070CAC */ .space 0x08

dlabel D_80070CB4
/* 718B4 80070CB4 */ .space 0x04

dlabel D_80070CB8
/* 718B8 80070CB8 */ .space 0x04

dlabel D_80070CBC
/* 718BC 80070CBC */ .space 0x24

dlabel D_80070CE0
/* 718E0 80070CE0 */ .space 0x08

dlabel D_80070CE8
/* 718E8 80070CE8 */ .space 0x28

dlabel D_80070D10
/* 71910 80070D10 */ .space 0x08

dlabel D_80070D18
/* 71918 80070D18 */ .space 0x108

dlabel D_80070E20
/* 71A20 80070E20 */ .space 0x08

dlabel D_80070E28
/* 71A28 80070E28 */ .space 0x84

dlabel D_80070EAC
/* 71AAC 80070EAC */ .space 0x04

dlabel D_80070EB0
/* 71AB0 80070EB0 */ .space 0x04

dlabel D_80070EB4
/* 71AB4 80070EB4 */ .space 0x5C8

dlabel D_8007147C
/* 7207C 8007147C */ .space 0x04

dlabel D_80071480
/* 72080 80071480 */ .space 0x04

dlabel D_80071484
/* 72084 80071484 */ .space 0x244C

dlabel D_800738D0
/* 744D0 800738D0 */ .space 0x5C0

dlabel D_80073E90
/* 74A90 80073E90 */ .space 0x08

dlabel D_80073E98
/* 74A98 80073E98 */ .space 0x18

dlabel D_80073EB0
/* 74AB0 80073EB0 */ .space 0x1C

dlabel D_80073ECC
/* 74ACC 80073ECC */ .space 0xC0

dlabel D_80073F8C
/* 74B8C 80073F8C */ .space 0x18

dlabel D_80073FA4
/* 74BA4 80073FA4 */ .space 0x04

dlabel D_80073FA8
/* 74BA8 80073FA8 */ .space 0xED8

dlabel D_80074E80
/* 75A80 80074E80 */ .space 0x40

dlabel D_80074EC0
/* 75AC0 80074EC0 */ .space 0x580

dlabel D_80075440
/* 76040 80075440 */ .space 0x02

dlabel D_80075442
/* 76042 80075442 */ .space 0x02

dlabel D_80075444
/* 76044 80075444 */ .space 0x14

dlabel D_80075458
/* 76058 80075458 */ .space 0x01

dlabel D_80075459
/* 76059 80075459 */ .space 0x01

dlabel D_8007545A
/* 7605A 8007545A */ .space 0x01

dlabel D_8007545B
/* 7605B 8007545B */ .space 0x0D

dlabel D_80075468
/* 76068 80075468 */ .space 0x68C8

dlabel D_8007BD30
/* 7C930 8007BD30 */ .space 0x04

dlabel D_8007BD34
/* 7C934 8007BD34 */ .space 0x04

dlabel D_8007BD38
/* 7C938 8007BD38 */ .space 0x08

dlabel D_8007BD40
/* 7C940 8007BD40 */ .space 0x20

dlabel D_8007BD60
/* 7C960 8007BD60 */ .space 0x04

dlabel D_8007BD64
/* 7C964 8007BD64 */ .space 0x5B4

dlabel D_8007C318
/* 7CF18 8007C318 */ .space 0xB8

dlabel D_8007C3D0
/* 7CFD0 8007C3D0 */ .space 0x08

dlabel D_8007C3D8
/* 7CFD8 8007C3D8 */ .space 0x58

dlabel D_8007C430
/* 7D030 8007C430 */ .space 0x08

dlabel D_8007C438
/* 7D038 8007C438 */ .space 0x1980

dlabel D_8007DDB8
/* 7E9B8 8007DDB8 */ .space 0x100

dlabel D_8007DEB8
/* 7EAB8 8007DEB8 */ .space 0x05

dlabel D_8007DEBD
/* 7EABD 8007DEBD */ .space 0x01

dlabel D_8007DEBE
/* 7EABE 8007DEBE */ .space 0x01

dlabel D_8007DEBF
/* 7EABF 8007DEBF */ .space 0x01

dlabel D_8007DEC0
/* 7EAC0 8007DEC0 */ .space 0x01

dlabel D_8007DEC1
/* 7EAC1 8007DEC1 */ .space 0x6F

dlabel D_8007DF30
/* 7EB30 8007DF30 */ .space 0x78

dlabel D_8007DFA8
/* 7EBA8 8007DFA8 */ .space 0x08

dlabel D_8007DFB0
/* 7EBB0 8007DFB0 */ .space 0x08

dlabel D_8007DFB8
/* 7EBB8 8007DFB8 */ .space 0x04

dlabel D_8007DFBC
/* 7EBBC 8007DFBC */ .space 0x14

dlabel D_8007DFD0
/* 7EBD0 8007DFD0 */ .space 0x3C

dlabel D_8007E00C
/* 7EC0C 8007E00C */ .space 0x04

dlabel D_8007E010
/* 7EC10 8007E010 */ .space 0x01

dlabel D_8007E011
/* 7EC11 8007E011 */ .space 0x01

dlabel D_8007E012
/* 7EC12 8007E012 */ .space 0x01

dlabel D_8007E013
/* 7EC13 8007E013 */ .space 0x01

dlabel D_8007E014
/* 7EC14 8007E014 */ .space 0x04

dlabel D_8007E018
/* 7EC18 8007E018 */ .space 0x04

dlabel D_8007E01C
/* 7EC1C 8007E01C */ .space 0x04

dlabel D_8007E020
/* 7EC20 8007E020 */ .space 0x04

dlabel D_8007E024
/* 7EC24 8007E024 */ .space 0x04

dlabel D_8007E028
/* 7EC28 8007E028 */ .space 0x04

dlabel D_8007E02C
/* 7EC2C 8007E02C */ .space 0x04

dlabel D_8007E030
/* 7EC30 8007E030 */ .space 0x04

dlabel D_8007E034
/* 7EC34 8007E034 */ .space 0x04

dlabel D_8007E038
/* 7EC38 8007E038 */ .space 0x04

dlabel D_8007E03C
/* 7EC3C 8007E03C */ .space 0x144

dlabel D_8007E180
/* 7ED80 8007E180 */ .space 0x18

dlabel D_8007E198
/* 7ED98 8007E198 */ .space 0x04

dlabel D_8007E19C
/* 7ED9C 8007E19C */ .space 0x01

dlabel D_8007E19D
/* 7ED9D 8007E19D */ .space 0x01

dlabel D_8007E19E
/* 7ED9E 8007E19E */ .space 0x01

dlabel D_8007E19F
/* 7ED9F 8007E19F */ .space 0x01

dlabel D_8007E1A0
/* 7EDA0 8007E1A0 */ .space 0x01

dlabel D_8007E1A1
/* 7EDA1 8007E1A1 */ .space 0x03

dlabel D_8007E1A4
/* 7EDA4 8007E1A4 */ .space 0x04

dlabel D_8007E1A8
/* 7EDA8 8007E1A8 */ .space 0x68

dlabel D_8007E210
/* 7EE10 8007E210 */ .space 0x18

dlabel D_8007E228
/* 7EE28 8007E228 */ .space 0x698

dlabel D_8007E8C0
/* 7F4C0 8007E8C0 */ .space 0x670

dlabel D_8007EF30
/* 7FB30 8007EF30 */ .space 0xD04

dlabel D_8007FC34
/* 80834 8007FC34 */ .space 0x04

dlabel D_8007FC38
/* 80838 8007FC38 */ .space 0x04

dlabel D_8007FC3C
/* 8083C 8007FC3C */ .space 0x04
